#!/bin/bash

set -eux

# ignore line longer than 80 chars
pycodestyle --exclude=.venv --ignore=E501,W503 focusd/

# is git installed and on the $PATH?
git help &> /dev/null

if [[ -n $(git diff --stat) ]]; then
    echo "Repo state dirty after ./reformat:"
    git diff --stat

    exit 1
fi