from typing import List

from jinja2 import Template

chrome_policy_template = """
{
    "IncognitoModeAvailability": 1,
    "BrowserGuestModeEnabled": false,
    "BrowserAddPersonEnabled": false,
    "BrowserSignin": 2,
    "ExtensionInstallForcelist": {{ plugin_id_list | tojson(indent=8)}}
}
"""

# /etc/hosts

hosts_template = """
{% for line in lines -%}
    {{ line.ip }} {{ line.dns_name }}
{% endfor %}
"""

resolv_conf_template = """
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.
{% for dns_server in dns_servers -%}
    nameserver {{ dns_server.ip }}
{% endfor -%}
nameserver 127.0.0.53
search nearmap.local"""
